import {initializeApp} from "https://www.gstatic.com/firebasejs/12.17.0/firebase-app.js";
import {getAuth,createUserWithEmailAndPassword,signInWithEmailAndPassword,signOut,onAuthStateChanged,updateProfile,GoogleAuthProvider,signInWithPopup} from "https://www.gstatic.com/firebasejs/12.17.0/firebase-auth.js";
import {getFirestore,collection,doc,setDoc,addDoc,query,where,onSnapshot,serverTimestamp,updateDoc} from "https://www.gstatic.com/firebasejs/12.17.0/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyBQxz-Oz3HhfcDr2jy15SjRcw6QHq1qBNY",authDomain:"chatss-daa4b.firebaseapp.com",projectId:"chatss-daa4b",storageBucket:"chatss-daa4b.firebasestorage.app",messagingSenderId:"482024813698",appId:"1:482024813698:web:4dde60bb2d14293423f09b"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);let currentUser=null,selectedUser=null,unUsers=null,unMessages=null,unReceipts=null,unTypingUser=null,unFriends=null,unIncoming=null,unOutgoing=null;let allUsers=new Map(),friendIds=new Set(),incoming=new Map(),outgoing=new Map(),currentMessages=[],receiptMap=new Map(),typingTimer=null;
function err(e){const m={"auth/invalid-email":"Неверный e-mail.","auth/invalid-credential":"Неверный e-mail или пароль.","auth/email-already-in-use":"Этот e-mail уже зарегистрирован.","auth/weak-password":"Пароль слишком простой.","auth/popup-closed-by-user":"Окно входа закрыто."};$("authError").textContent=m[e?.code]||e?.message||"Ошибка.";console.error(e)}
$("signupBtn").onclick=async()=>{try{const email=$("email").value.trim(),password=$("password").value,name=$("displayName").value.trim()||email.split("@")[0],c=await createUserWithEmailAndPassword(auth,email,password);await updateProfile(c.user,{displayName:name});await setDoc(doc(db,"users",c.user.uid),{uid:c.user.uid,name,email,status:"online",lastSeen:serverTimestamp(),typingTo:null})}catch(e){err(e)}};
$("loginBtn").onclick=async()=>{try{await signInWithEmailAndPassword(auth,$("email").value.trim(),$("password").value)}catch(e){err(e)}};
$("googleBtn").onclick=async()=>{try{const c=await signInWithPopup(auth,new GoogleAuthProvider());await setDoc(doc(db,"users",c.user.uid),{uid:c.user.uid,name:c.user.displayName||"User",email:c.user.email,status:"online",lastSeen:serverTimestamp(),typingTo:null},{merge:true})}catch(e){err(e)}};
$("logoutBtn").onclick=()=>signOut(auth);
onAuthStateChanged(auth,async u=>{currentUser=u;if(!u){$("authScreen").classList.remove("hidden");$("app").classList.add("hidden");return}$("authScreen").classList.add("hidden");$("app").classList.remove("hidden");$("myName").textContent=u.displayName||u.email.split("@")[0];$("myEmail").textContent=u.email;$("myAvatar").textContent=(u.displayName||u.email)[0].toUpperCase();await setDoc(doc(db,"users",u.uid),{uid:u.uid,name:u.displayName||u.email.split("@")[0],email:u.email,status:"online",lastSeen:serverTimestamp(),typingTo:null},{merge:true}).catch(console.error);loadUsers();loadFriends();loadRequests()});
function loadUsers(){if(unUsers)unUsers();unUsers=onSnapshot(query(collection(db,"users")),s=>{allUsers.clear();s.forEach(d=>allUsers.set(d.id,d.data()));renderLists()},e=>console.error("Users:",e))}
function loadFriends(){if(unFriends)unFriends();unFriends=onSnapshot(query(collection(db,"friendships"),where("participants","array-contains",currentUser.uid)),s=>{friendIds=new Set();s.forEach(d=>(d.data().participants||[]).forEach(id=>{if(id!==currentUser.uid)friendIds.add(id)}));renderLists();updateFriendButton()},e=>console.error("Friends:",e))}
function loadRequests(){if(unIncoming)unIncoming();if(unOutgoing)unOutgoing();unIncoming=onSnapshot(query(collection(db,"friendRequests"),where("toId","==",currentUser.uid)),s=>{incoming.clear();s.forEach(d=>{const r=d.data();if(r.status==="pending")incoming.set(d.id,{id:d.id,...r})});renderRequests();updateFriendButton()},e=>console.error("Incoming:",e));unOutgoing=onSnapshot(query(collection(db,"friendRequests"),where("fromId","==",currentUser.uid)),s=>{outgoing.clear();s.forEach(d=>{const r=d.data();if(r.status==="pending")outgoing.set(r.toId,{id:d.id,...r})});renderLists();updateFriendButton()},e=>console.error("Outgoing:",e))}
function renderLists(){const term=$("searchUsers").value.toLowerCase();$("friendsList").innerHTML="";friendIds.forEach(id=>{const u=allUsers.get(id);if(u)$("friendsList").appendChild(userEl(u))});$("usersList").innerHTML="";for(const[id,u]of allUsers){if(id===currentUser.uid||friendIds.has(id)||!`${u.name||""} ${u.email||""}`.toLowerCase().includes(term))continue;$("usersList").appendChild(userEl(u))}}
function userEl(u){const e=document.createElement("div");e.className="user"+(selectedUser?.uid===u.uid?" active":"");e.innerHTML=`<div class="avatar">${esc((u.name||"U")[0].toUpperCase())}</div><div><b>${esc(u.name||"User")}</b><div class="${u.status==="online"?"online":"offline"}">● ${u.status==="online"?"В сети":"Не в сети"}</div></div>`;e.onclick=()=>openChat(u);return e}$("searchUsers").oninput=renderLists;
function renderRequests(){const box=$("requestsList");box.innerHTML="";let count=0;incoming.forEach(r=>{count++;const u=allUsers.get(r.fromId);if(!u)return;const e=document.createElement("div");e.className="request";e.innerHTML=`<div class="request-main"><div class="avatar small">${esc((u.name||"U")[0].toUpperCase())}</div><div><b>${esc(u.name||"User")}</b><small>хочет добавить вас</small></div></div><div class="request-actions"><button class="accept">✓</button><button class="decline">×</button></div>`;e.querySelector(".accept").onclick=()=>acceptRequest(r);e.querySelector(".decline").onclick=()=>declineRequest(r);box.appendChild(e)});$("requestCount").textContent=count;$("requestCount").classList.toggle("hidden",count===0);if(!count)box.innerHTML='<div class="no-requests">Нет новых заявок</div>'}
async function sendFriendRequest(){if(!selectedUser||friendIds.has(selectedUser.uid)||outgoing.has(selectedUser.uid))return;try{const ref=doc(collection(db,"friendRequests"));await setDoc(ref,{fromId:currentUser.uid,toId:selectedUser.uid,status:"pending",createdAt:serverTimestamp()});updateFriendButton()}catch(e){alert("Не удалось отправить заявку: "+e.message)}}
async function acceptRequest(r){try{const participants=[r.fromId,r.toId].sort();await setDoc(doc(db,"friendships",participants.join("_")),{participants,createdAt:serverTimestamp()});await updateDoc(doc(db,"friendRequests",r.id),{status:"accepted",respondedAt:serverTimestamp()})}catch(e){alert("Не удалось принять заявку: "+e.message)}}
async function declineRequest(r){try{await updateDoc(doc(db,"friendRequests",r.id),{status:"declined",respondedAt:serverTimestamp()})}catch(e){console.error(e)}}
function updateFriendButton(){if(!selectedUser)return;const b=$("friendBtn"),id=selectedUser.uid;if(friendIds.has(id)){b.textContent="✓ В друзьях";b.disabled=true;b.className="friend-btn friend-ok"}else if(outgoing.has(id)){b.textContent="⏳ Заявка отправлена";b.disabled=true;b.className="friend-btn"}else if(incoming.has(id)){b.textContent="✓ Принять заявку";b.disabled=false;b.className="friend-btn";b.onclick=()=>acceptRequest(incoming.get(id))}else{b.textContent="+ Добавить в друзья";b.disabled=false;b.className="friend-btn";b.onclick=sendFriendRequest}}
const chatId=(a,b)=>[a,b].sort().join("_");
function renderMessages(){const box=$("messages");box.innerHTML="";currentMessages.forEach(m=>{const mine=m.senderId===currentUser.uid,e=document.createElement("div");e.className="msg"+(mine?" mine":"");const tm=m.createdAtMs?new Date(m.createdAtMs).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}):"";let status="";if(mine){const r=receiptMap.get(m.id);status=r?.readAt?"✓✓ Прочитано":r?.deliveredAt?"✓ Доставлено":"✓ Отправлено"}e.innerHTML=`<div class="bubble">${esc(m.text||"")}</div><div class="time">${tm}</div>${mine?`<div class="msg-meta">${status}</div>`:""}`;box.appendChild(e)});box.scrollTop=box.scrollHeight}
async function markReceipt(messageId,id){try{await setDoc(doc(db,"messageReceipts",messageId),{messageId,chatId:id,participants:[currentUser.uid,selectedUser.uid].sort(),readerId:currentUser.uid,deliveredAt:serverTimestamp(),readAt:serverTimestamp()},{merge:true})}catch(e){console.error("Receipt:",e)}}
function openChat(u){selectedUser=u;$("emptyChat").classList.add("hidden");$("chatPanel").classList.remove("hidden");$("chatName").textContent=u.name;$("chatStatus").textContent=u.status==="online"?"🟢 В сети":"⚪ Не в сети";$("chatAvatar").textContent=(u.name||"U")[0].toUpperCase();updateFriendButton();if(unMessages)unMessages();if(unReceipts)unReceipts();if(unTypingUser)unTypingUser();currentMessages=[];receiptMap=new Map();const id=chatId(currentUser.uid,u.uid);
unMessages=onSnapshot(query(collection(db,"messages"),where("participants","array-contains",currentUser.uid)),s=>{currentMessages=[];s.forEach(d=>{const m=d.data();if(m.chatId===id)currentMessages.push({id:d.id,...m})});currentMessages.sort((a,b)=>(a.createdAtMs||0)-(b.createdAtMs||0));currentMessages.filter(m=>m.senderId!==currentUser.uid).forEach(m=>markReceipt(m.id,id));renderMessages()},e=>{$("messages").innerHTML='<div style="padding:15px;color:#a40000">Ошибка загрузки сообщений: '+esc(e.message)+'</div>';console.error(e)});
unReceipts=onSnapshot(query(collection(db,"messageReceipts"),where("participants","array-contains",currentUser.uid)),s=>{receiptMap=new Map();s.forEach(d=>{const r=d.data();if(r.chatId===id)receiptMap.set(d.id,r)});renderMessages()},e=>console.error("Receipts:",e));
unTypingUser=onSnapshot(doc(db,"users",u.uid),s=>{const data=s.data()||{};const active=data.typingTo===id;$("typingIndicator").classList.toggle("hidden",!active)},e=>console.error("Typing user:",e));}
async function setTyping(value){if(!currentUser||!selectedUser)return;const id=chatId(currentUser.uid,selectedUser.uid);try{await updateDoc(doc(db,"users",currentUser.uid),{typingTo:value?id:null,typingAt:value?serverTimestamp():null})}catch(e){console.error("Typing:",e)}}
$("messageInput").addEventListener("input",()=>{if(!selectedUser)return;setTyping(true);clearTimeout(typingTimer);typingTimer=setTimeout(()=>setTyping(false),1300)});
$("messageInput").addEventListener("blur",()=>{clearTimeout(typingTimer);setTyping(false)});
$("messageForm").onsubmit=async e=>{e.preventDefault();const text=$("messageInput").value.trim();if(!text||!selectedUser||!currentUser)return;const input=$("messageInput"),btn=e.submitter;input.disabled=true;if(btn)btn.disabled=true;clearTimeout(typingTimer);await setTyping(false);try{await addDoc(collection(db,"messages"),{chatId:chatId(currentUser.uid,selectedUser.uid),participants:[currentUser.uid,selectedUser.uid].sort(),text,senderId:currentUser.uid,receiverId:selectedUser.uid,createdAt:serverTimestamp(),createdAtMs:Date.now()});input.value=""}catch(e){err(e)}finally{input.disabled=false;if(btn)btn.disabled=false;input.focus()}};
const emojis=["😀","😁","😂","🤣","😊","😍","😘","😎","🤔","😢","😭","😡","👍","👎","❤️","🔥","🎉","😉","😇","🤝","🙏","💪","👋","😴","😱","😅","🥰","💙","✨"];
$("emojiPanel").innerHTML=emojis.map(x=>`<button type="button">${x}</button>`).join("");$("emojiBtn").onclick=()=>$("emojiPanel").classList.toggle("hidden");$("emojiPanel").onclick=e=>{if(e.target.tagName!=="BUTTON")return;$("messageInput").value+=e.target.textContent;$("messageInput").focus();setTyping(true)};
$("statusBtn").onclick=async()=>{try{const n=$("statusBtn").textContent.includes("В сети")?"offline":"online";await updateDoc(doc(db,"users",currentUser.uid),{status:n,lastSeen:serverTimestamp()});$("statusBtn").textContent=n==="online"?"🟢 В сети":"⚪ Не в сети"}catch(e){console.error(e)}};
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}