import {initializeApp} from "https://www.gstatic.com/firebasejs/12.17.0/firebase-app.js";
import {getAuth,createUserWithEmailAndPassword,signInWithEmailAndPassword,signOut,onAuthStateChanged,updateProfile,GoogleAuthProvider,signInWithPopup} from "https://www.gstatic.com/firebasejs/12.17.0/firebase-auth.js";
import {getFirestore,collection,doc,setDoc,getDoc,addDoc,query,where,onSnapshot,serverTimestamp,updateDoc} from "https://www.gstatic.com/firebasejs/12.17.0/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyBQxz-Oz3HhfcDr2jy15SjRcw6QHq1qBNY",authDomain:"chatss-daa4b.firebaseapp.com",projectId:"chatss-daa4b",storageBucket:"chatss-daa4b.firebasestorage.app",messagingSenderId:"482024813698",appId:"1:482024813698:web:4dde60bb2d14293423f09b"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);const $=id=>document.getElementById(id);
let currentUser=null,selectedUser=null,unUsers=null,unMessages=null,unFriends=null,unIncoming=null,unOutgoing=null;
let allUsers=new Map(),friendIds=new Set(),incoming=new Map(),outgoing=new Map();

function err(e){const m={"auth/invalid-email":"Неверный e-mail.","auth/invalid-credential":"Неверный e-mail или пароль.","auth/email-already-in-use":"Этот e-mail уже зарегистрирован.","auth/weak-password":"Пароль слишком простой.","auth/popup-closed-by-user":"Окно входа закрыто."};$("authError").textContent=m[e?.code]||e?.message||"Ошибка.";console.error(e)}
$("signupBtn").onclick=async()=>{try{const email=$("email").value.trim(),password=$("password").value,name=$("displayName").value.trim()||email.split("@")[0];const c=await createUserWithEmailAndPassword(auth,email,password);await updateProfile(c.user,{displayName:name});await setDoc(doc(db,"users",c.user.uid),{uid:c.user.uid,name,email,status:"online",lastSeen:serverTimestamp()});}catch(e){err(e)}};
$("loginBtn").onclick=async()=>{try{await signInWithEmailAndPassword(auth,$("email").value.trim(),$("password").value)}catch(e){err(e)}};
$("googleBtn").onclick=async()=>{try{const c=await signInWithPopup(auth,new GoogleAuthProvider());await setDoc(doc(db,"users",c.user.uid),{uid:c.user.uid,name:c.user.displayName||"User",email:c.user.email,status:"online",lastSeen:serverTimestamp()},{merge:true});}catch(e){err(e)}};
$("logoutBtn").onclick=()=>signOut(auth);

onAuthStateChanged(auth,async u=>{currentUser=u;if(!u){$("authScreen").classList.remove("hidden");$("app").classList.add("hidden");return}
$("authScreen").classList.add("hidden");$("app").classList.remove("hidden");$("myName").textContent=u.displayName||u.email.split("@")[0];$("myEmail").textContent=u.email;$("myAvatar").textContent=(u.displayName||u.email)[0].toUpperCase();
try{await setDoc(doc(db,"users",u.uid),{uid:u.uid,name:u.displayName||u.email.split("@")[0],email:u.email,status:"online",lastSeen:serverTimestamp()},{merge:true});}catch(e){console.error(e)}
loadUsers();loadFriends();loadRequests();});

function loadUsers(){if(unUsers)unUsers();unUsers=onSnapshot(query(collection(db,"users")),s=>{allUsers.clear();s.forEach(d=>allUsers.set(d.id,d.data()));renderLists()},e=>console.error("Users listener:",e))}
function loadFriends(){if(unFriends)unFriends();unFriends=onSnapshot(query(collection(db,"friendships"),where("participants","array-contains",currentUser.uid)),s=>{friendIds=new Set();s.forEach(d=>{const p=d.data().participants||[];p.forEach(id=>{if(id!==currentUser.uid)friendIds.add(id)})});renderLists();updateFriendButton()},e=>console.error("Friends listener:",e))}
function loadRequests(){if(unIncoming)unIncoming();if(unOutgoing)unOutgoing();
unIncoming=onSnapshot(query(collection(db,"friendRequests"),where("toId","==",currentUser.uid)),s=>{incoming.clear();s.forEach(d=>{const r=d.data();if(r.status==="pending")incoming.set(d.id,{id:d.id,...r})});renderRequests();updateFriendButton()},e=>console.error("Incoming requests:",e));
unOutgoing=onSnapshot(query(collection(db,"friendRequests"),where("fromId","==",currentUser.uid)),s=>{outgoing.clear();s.forEach(d=>{const r=d.data();if(r.status==="pending")outgoing.set(r.toId,{id:d.id,...r})});renderLists();updateFriendButton()},e=>console.error("Outgoing requests:",e));}

function renderLists(){const term=$("searchUsers").value.toLowerCase();$("friendsList").innerHTML="";friendIds.forEach(id=>{const u=allUsers.get(id);if(u)$("friendsList").appendChild(userEl(u,true))});$("usersList").innerHTML="";for(const [id,u] of allUsers){if(id===currentUser.uid||friendIds.has(id)||!`${u.name||""} ${u.email||""}`.toLowerCase().includes(term))continue;$("usersList").appendChild(userEl(u,false))}}
function userEl(u,isFriend){const e=document.createElement("div");e.className="user"+(selectedUser?.uid===u.uid?" active":"");e.innerHTML=`<div class="avatar">${esc((u.name||"U")[0].toUpperCase())}</div><div><b>${esc(u.name||"User")}</b><div class="${u.status==="online"?"online":"offline"}">● ${u.status==="online"?"В сети":"Не в сети"}</div></div>`;e.onclick=()=>openChat(u);return e}
$("searchUsers").oninput=renderLists;

function renderRequests(){const box=$("requestsList");box.innerHTML="";let count=0;incoming.forEach(r=>{count++;const u=allUsers.get(r.fromId);if(!u)return;const e=document.createElement("div");e.className="request";e.innerHTML=`<div class="request-main"><div class="avatar small">${esc((u.name||"U")[0].toUpperCase())}</div><div><b>${esc(u.name||"User")}</b><small>хочет добавить вас</small></div></div><div class="request-actions"><button class="accept">✓</button><button class="decline">×</button></div>`;e.querySelector(".accept").onclick=()=>acceptRequest(r);e.querySelector(".decline").onclick=()=>declineRequest(r);box.appendChild(e)});$("requestCount").textContent=count;$("requestCount").classList.toggle("hidden",count===0);if(!count)box.innerHTML='<div class="no-requests">Нет новых заявок</div>'}

async function sendFriendRequest(){if(!selectedUser||friendIds.has(selectedUser.uid))return;const existing=outgoing.get(selectedUser.uid);if(existing)return;try{const ref=doc(collection(db,"friendRequests"));await setDoc(ref,{fromId:currentUser.uid,toId:selectedUser.uid,status:"pending",createdAt:serverTimestamp()});updateFriendButton()}catch(e){console.error(e);alert("Не удалось отправить заявку: "+e.message)}}
async function acceptRequest(r){try{const participants=[r.fromId,r.toId].sort();const id=participants.join("_");await setDoc(doc(db,"friendships",id),{participants,createdAt:serverTimestamp()});await updateDoc(doc(db,"friendRequests",r.id),{status:"accepted",respondedAt:serverTimestamp()});}catch(e){console.error(e);alert("Не удалось принять заявку: "+e.message)}}
async function declineRequest(r){try{await updateDoc(doc(db,"friendRequests",r.id),{status:"declined",respondedAt:serverTimestamp()})}catch(e){console.error(e)}}

function updateFriendButton(){if(!selectedUser)return;const b=$("friendBtn"),id=selectedUser.uid;if(friendIds.has(id)){b.textContent="✓ В друзьях";b.disabled=true;b.className="friend-btn friend-ok"}else if(outgoing.has(id)){b.textContent="⏳ Заявка отправлена";b.disabled=true;b.className="friend-btn"}else if(incoming.has(id)){b.textContent="✓ Принять заявку";b.disabled=false;b.className="friend-btn";b.onclick=()=>acceptRequest(incoming.get(id))}else{b.textContent="+ Добавить в друзья";b.disabled=false;b.className="friend-btn";b.onclick=sendFriendRequest}}

const chatId=(a,b)=>[a,b].sort().join("_");
function renderMessage(m){const mine=m.senderId===currentUser.uid,e=document.createElement("div");e.className="msg"+(mine?" mine":"");const tm=m.createdAtMs?new Date(m.createdAtMs).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}):"";e.innerHTML=`<div class="bubble">${esc(m.text||"")}</div><div class="time">${tm}</div>`;return e}
function openChat(u){selectedUser=u;$("emptyChat").classList.add("hidden");$("chatPanel").classList.remove("hidden");$("chatName").textContent=u.name;$("chatStatus").textContent=u.status==="online"?"🟢 В сети":"⚪ Не в сети";$("chatAvatar").textContent=(u.name||"U")[0].toUpperCase();updateFriendButton();if(unMessages)unMessages();const id=chatId(currentUser.uid,u.uid);const q=query(collection(db,"messages"),where("participants","array-contains",currentUser.uid));unMessages=onSnapshot(q,s=>{const arr=[];s.forEach(d=>{const m=d.data();if(m.chatId===id)arr.push(m)});arr.sort((a,b)=>(a.createdAtMs||0)-(b.createdAtMs||0));$("messages").innerHTML="";arr.forEach(m=>$("messages").appendChild(renderMessage(m)));$("messages").scrollTop=$("messages").scrollHeight},e=>{$("messages").innerHTML='<div style="padding:15px;color:#a40000">Ошибка загрузки сообщений: '+esc(e.message)+'</div>';console.error("Messages listener:",e)})}

$("messageForm").onsubmit=async e=>{e.preventDefault();const text=$("messageInput").value.trim();if(!text||!selectedUser||!currentUser)return;const participants=[currentUser.uid,selectedUser.uid].sort(),input=$("messageInput"),sendBtn=e.submitter;input.disabled=true;if(sendBtn)sendBtn.disabled=true;try{await addDoc(collection(db,"messages"),{chatId:chatId(currentUser.uid,selectedUser.uid),participants,text,senderId:currentUser.uid,receiverId:selectedUser.uid,createdAt:serverTimestamp(),createdAtMs:Date.now()});input.value=""}catch(e){err(e)}finally{input.disabled=false;if(sendBtn)sendBtn.disabled=false;input.focus()}};

const emojis=["😀","😁","😂","🤣","😊","😍","😘","😎","🤔","😢","😭","😡","👍","👎","❤️","🔥","🎉","😂","😉","😇","🤝","🙏","💪","👋","😴","😱","😅","🥰","💙","✨"];
$("emojiPanel").innerHTML=emojis.map(x=>`<button type="button">${x}</button>`).join("");$("emojiBtn").onclick=()=>$("emojiPanel").classList.toggle("hidden");$("emojiPanel").onclick=e=>{if(e.target.tagName!=="BUTTON")return;const i=$("messageInput");i.value+=e.target.textContent;i.focus()};
$("statusBtn").onclick=async()=>{try{const online=$("statusBtn").textContent.includes("В сети"),n=online?"offline":"online";await updateDoc(doc(db,"users",currentUser.uid),{status:n,lastSeen:serverTimestamp()});$("statusBtn").textContent=n==="online"?"🟢 В сети":"⚪ Не в сети"}catch(e){console.error(e)}};
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}